### ISSUE TITLE
Possible Error in the Time Update of the Particles

### ISSUE THREAD

**Issue by Kumru** [aeblc/particle_filter_matlab#1]
https://github.com/aeblc/particle_filter_matlab/blob/f279310e6a2c640d56f8c3d027709f5740e30ae5/particleFilterGeneric.m#L47-L56

I believe the `chol(Q)` statements should be replaced by `transpose(chol(Q))` in the referenced section.

**Comment by aeblc** [comment]
I assumed, without checking the actual function, that `chol(Q)` yields a lower triangular matrix. Thank you for pointing that out!

**Comment by aeblc** [comment]
Corrected at https://github.com/aeblc/particle_filter_matlab/commit/131d3cb343b112c1b9caab4907c289d057cb63aa by specifically stating that the resulting matrix should be lower triangular using the second function argument to avoid any confusion. Otherwise an outsider might think that `chol(Q)` already yields a lower triangular matrix, as I did before, and the transposition operation is unnecessary.
